coverage:
  precision: 2
  round: down
  range: '80...100'
  status:
    project:
      default:
        target: 80%
        threshold: 5%
    patch:
      default:
        target: 80%
        threshold: 5%

comment:
  layout: 'reach, diff, flags, files'
  behavior: default
  require_changes: false

parsers:
  gcov:
    enable: true
  lcov:
    enable: true

ignore:
  - 'src/**/*.stories.tsx'
  - 'src/styles/**/*'
  - 'src/types/**/*.d.ts'
  - 'src/utils/**/*'
  - 'src/hooks/**/*'
  - 'src/**/mock.ts(x)?'
  - '**/*.test.ts(x)?'
  - '**/*.spec.ts(x)?'
  - '**/node_modules/**'
  - '**/coverage/**'
  - '**/.jest/**'
  - '**/dist/**'
  - '**/build/**'
