name: Commit Notifications

on:
  push:
    branches:
      - main
      - develop
      - feature/*
      - hotfix/*

jobs:
  notify-commit:
    name: Notify Commit Status
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Create Commit Comment
        uses: actions/github-script@v7
        with:
          script: |
            const commitSha = context.sha;
            const branch = context.ref.replace('refs/heads/', '');
            const repo = context.repo;

            try {
              // Tenta criar um comentário no commit
              await github.rest.repos.createCommitComment({
                owner: repo.owner,
                repo: repo.repo,
                commit_sha: commitSha,
                body: `🚀 **Commit Deployed Successfully**
                
                **Branch**: ${branch}
                **Commit**: ${commitSha}
                **Author**: ${context.payload.head_commit.author.name}
                **Message**: ${context.payload.head_commit.message}
                
                [View Commit](https://github.com/${repo.owner}/${repo.repo}/commit/${commitSha})
                
                ✅ All checks passed and deployment completed.`
              });
              
              console.log('Commit comment created successfully');
            } catch (error) {
              console.log('Could not create commit comment:', error.message);
              console.log('This is normal for some repository configurations');
            }
