name: Status Notifications

on:
  workflow_run:
    workflows:
      [
        'CI/CD Pipeline',
        'Security & Dependencies',
        'Performance & Bundle Analysis'
      ]
    types:
      - completed

jobs:
  status-notify:
    name: Update Status Checks
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion != 'skipped' }}

    steps:
      - name: Update Commit Status
        uses: actions/github-script@v7
        with:
          script: |
            const workflowRun = context.payload.workflow_run;
            const headSha = workflowRun.head_sha;
            const conclusion = workflowRun.conclusion;
            const workflowName = workflowRun.name;
            
            console.log('Updating commit status for:', headSha);
            console.log('Workflow:', workflowName);
            console.log('Conclusion:', conclusion);
            
            let status = 'success';
            let description = 'All checks passed';
            
            if (conclusion === 'failure') {
              status = 'failure';
              description = 'Some checks failed';
            } else if (conclusion === 'cancelled') {
              status = 'cancelled';
              description = 'Workflow was cancelled';
            }
            
            try {
              await github.rest.repos.createCommitStatus({
                owner: context.repo.owner,
                repo: context.repo.repo,
                sha: headSha,
                state: status,
                target_url: workflowRun.html_url,
                description: `${workflowName}: ${description}`,
                context: `ci/${workflowName.toLowerCase().replace(/[^a-z0-9]/g, '-')}`
              });
              
              console.log('Status updated successfully');
            } catch (error) {
              console.log('Error updating status:', error.message);
            } 